# Generated by Django 5.0 on 2024-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_ticket_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
    ]
