# Generated by Django 5.0 on 2024-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ticket_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
